language : node_js
node_js :
  - "12.16.1"
script :
  - echo "Deploying"
install :
  - npm install -g firebase-tools
  - npm install
  - npm run build
after-success:
  - firebase deploy --token $FIREBASE_TOKEN